Repository Naval-Base/yuudachi, pull requests merged in 2020-11, with the labels that each got.

#784 refactor(tags): split subcommands into sub folder
  src/api/src/middleware/authenticate.test.ts
  src/handler/src/commands/tags/sub/add.ts
  src/handler/src/commands/tags/sub/alias.ts
  src/handler/src/commands/tags/sub/remove.ts
  src/handler/src/commands/tags/sub/update.ts
  src/handler/src/commands/tags/tag.ts
Labels: handler, refactor, semver:minor

#785 feat(logs): log messages without content, log multiple attachments
  src/bot/listeners/client/guildLog/messageDelete.ts
Labels: refactor, semver:minor

#786 feat: add antiraid functionality
  src/bot/commands/mod/antiraid.ts
  src/bot/listeners/client/moderation/guildMemberAdd.ts
  src/bot/util/constants.ts
Labels: semver:minor

#791 chore: consistent day defaulting and bounds
  src/bot/commands/mod/ban.ts
  src/bot/commands/mod/softban.ts
Labels: semver:major

#790 feat(cybernuke): improve verbosity and ux
  src/bot/commands/util/cybernuke.ts
  src/bot/util/constants.ts
Labels: refactor, semver:major

#789 feat: multi ban command
  src/bot/commands/mod/multiban.ts
  src/bot/util/constants.ts
Labels: semver:minor

#787 fix(antiraid): rework to execute actions
  src/bot/listeners/client/moderation/guildMemberAdd.ts
  src/bot/util/constants.ts
Labels: refactor, regression, semver:patch

#792 feat(*): ux improvements
  src/bot/commands/mod/multiban.ts
  src/bot/commands/util/cybernuke.ts
  src/bot/listeners/client/memberLog/guildMemberAdd.ts
  src/bot/listeners/client/memberLog/guildMemberRemove.ts
  src/bot/structures/CaseHandler.ts
  src/bot/util/constants.ts
Labels: regression, semver:patch

#793 fix(cybernuke): regression from #792
  src/bot/commands/util/cybernuke.ts
  src/bot/listeners/client/memberLog/guildMemberAdd.ts
  src/bot/listeners/client/memberLog/guildMemberRemove.ts
Labels: regression, semver:patch

#794 feat(website): guilds view
  hasura/migrations/1586479065565_next/down.sql
  hasura/migrations/1586479065565_next/up.sql
  hasura/optional_migrations/1586479065565_next/down.sql
  hasura/optional_migrations/1586479065565_next/up.sql
  package-lock.json
  package.json
  packages/api/package.json
  packages/rest/package.json
  packages/types/package.json
  src/api/package.json
  src/api/src/managers/AuthManager.test.ts
  src/api/src/managers/AuthManager.ts
  src/api/src/middleware/authenticate.test.ts
  src/api/src/middleware/authenticate.ts
  src/api/src/middleware/session.ts
  src/api/src/routes/auth/discord/callback/get.ts
  src/api/src/routes/auth/refresh/get.ts
  src/api/src/routes/guilds/get.ts
  src/api/src/routes/users/me/get.ts
  src/bot/commands/mod/antiraid.ts
  src/bot/commands/mod/multiban.ts
  src/bot/listeners/client/moderation/guildMemberAdd.ts
  src/handler/package.json
  src/website/package-lock.json
  src/website/package.json
  src/website/src/components/GuildSettings.tsx
  src/website/src/components/Guilds.tsx
  src/website/src/components/Layout.tsx
  src/website/src/components/Navbar.tsx
  src/website/src/hooks/useMutationInsertGuildSettings.ts
  src/website/src/hooks/useMutationUpdateGuildSettings.ts
  src/website/src/hooks/useQueryGuildSettings.ts
  src/website/src/hooks/useQueryGuilds.ts
  src/website/src/interfaces/Guild.ts
  src/website/src/interfaces/GuildSettings.ts
  src/website/src/pages/_app.tsx
  src/website/src/pages/guild/[id].tsx
  src/website/src/pages/index.tsx
  src/website/src/pages/user/me.tsx
  src/website/src/styles/modules/Guilds.module.scss
  src/website/src/util/fetch.ts
  src/website/src/util/fetchGraphQL.ts
Labels: api, in progress, semver:major, website

#750 feat: add send permissions inhibitor
  src/bot/inhibitors/sendPermissions.ts
Labels: semver:minor

#796 feat(*): various qol features
  src/bot/commands/info/user.ts
  src/bot/commands/mod/antiraid.ts
  src/bot/commands/mod/cases/show.ts
  src/bot/commands/mod/history.ts
  src/bot/commands/mod/multiban.ts
  src/bot/commands/tag/info.ts
  src/bot/commands/util/cybernuke.ts
  src/bot/listeners/client/moderation/guildMemberAdd.ts
  src/bot/structures/CaseHandler.ts
  src/bot/structures/case/actions/Action.ts
  src/bot/structures/case/actions/Ban.ts
  src/bot/util/constants.ts
  src/bot/util/graphQL.ts
Labels: refactor, semver:minor

#798 fix(*): use before for member resolving
  src/bot/commands/mod/multiban.ts
  src/bot/commands/util/cybernuke.ts
Labels: semver:minor

#799 fix(api/auth): properly split auth from api and rework public endpoints to hasura actions
  .gitignore
  docker-compose.local.yml
  docker-compose.prod.yml
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  packages/core/src/Constants.ts
  src/api/bin/index.ts
  src/api/src/middleware/authorize.test.ts
  src/api/src/middleware/authorize.ts
  src/api/src/middleware/index.ts
  src/api/src/routes/guilds/[guildId]/cases/post.test.ts
  src/api/src/routes/guilds/[guildId]/cases/post.ts
  src/api/src/routes/guilds/get.ts
  src/api/src/routes/hasura/actions/guilds/post.ts
  src/api/src/routes/hasura/actions/me/post.ts
  src/api/src/routes/hasura/actions/mod_action/post.ts
  src/api/src/routes/users/me/get.ts
  src/website/src/components/Guilds.tsx
  src/website/src/components/Layout.tsx
  src/website/src/hooks/useQueryGuilds.ts
  src/website/src/hooks/useQueryMe.ts
  src/website/src/interfaces/Connection.ts
  src/website/src/interfaces/Guild.ts
  src/website/src/interfaces/Guilds.ts
  src/website/src/interfaces/User.ts
  src/website/src/pages/guild/[id].tsx
  src/website/src/util/fetch.ts
Labels: api, refactor, semver:major, website
