Repository Naval-Base/yuudachi, pull requests merged in 2022-08, with the labels that each got.

#1080 feat(logs): log replies in message deletions
  packages/yuudachi/locales/en-US/translation.json
  packages/yuudachi/src/events/guild-log/messageDelete.ts
  packages/yuudachi/src/events/guild-log/messageDeleteBulk.ts
  packages/yuudachi/src/events/guild-log/messageUpdate.ts
Labels: semver:minor

#1083 feat(commands): message clear command
  packages/yuudachi/locales/en-US/translation.json
  packages/yuudachi/src/Constants.ts
  packages/yuudachi/src/commands/moderation/clear.ts
  packages/yuudachi/src/commands/moderation/duration.ts
  packages/yuudachi/src/commands/moderation/reason.ts
  packages/yuudachi/src/commands/moderation/reference.ts
  packages/yuudachi/src/deploy.ts
  packages/yuudachi/src/events/guild-log/messageDeleteBulk.ts
  packages/yuudachi/src/functions/logging/formatMessagesToAttachment.ts
  packages/yuudachi/src/functions/logging/generateCaseLog.ts
  packages/yuudachi/src/functions/pruning/pruneMessages.ts
  packages/yuudachi/src/interactions/index.ts
  packages/yuudachi/src/interactions/moderation/clear.ts
  packages/yuudachi/src/util/generateHistory.ts
  packages/yuudachi/src/util/generateMessageLink.ts
Labels: semver:minor

#1094 feat(*): improve message context commands
  packages/yuudachi/locales/en-US/translation.json
  packages/yuudachi/src/commands/moderation/clear.ts
  packages/yuudachi/src/commands/utility/repost.ts
  packages/yuudachi/src/deploy.ts
  packages/yuudachi/src/functions/logging/formatMessageToEmbed.ts
  packages/yuudachi/src/interactions/context-menu/clear.ts
  packages/yuudachi/src/interactions/index.ts
  packages/yuudachi/src/util/resolveMessages.ts
Labels: semver:minor

#1093 fix(anti-raid): do not create case on dry-run
  packages/yuudachi/src/functions/anti-raid/blastOff.ts
Labels: priority:high, semver:patch

#1091 refactor: Improve automod handling
  packages/yuudachi/locales/en-US/translation.json
  packages/yuudachi/src/events/anti-scam/messageCreate.ts
  packages/yuudachi/src/events/anti-spam/autoModerationActionExecute.ts
  packages/yuudachi/src/events/anti-spam/messageCreate.ts
  packages/yuudachi/src/events/manual-timeout/autoModerationActionExecute.ts
  packages/yuudachi/src/events/manual-timeout/guildMemberUpdate.ts
  packages/yuudachi/src/functions/anti-spam/considerableText.ts
  packages/yuudachi/src/functions/anti-spam/handler.ts
  packages/yuudachi/src/functions/anti-spam/totalContents.ts
  packages/yuudachi/src/functions/anti-spam/totalMentions.ts
  packages/yuudachi/src/index.ts
  packages/yuudachi/src/util/tempAutomodTypes.ts
Labels: semver:minor

#1108 feat(nuke): extended nuke protection
  packages/yuudachi/locales/en-US/translation.json
  packages/yuudachi/src/Constants.ts
  packages/yuudachi/src/commands/moderation/anti-raid-nuke.ts
  packages/yuudachi/src/commands/moderation/sub/anti-raid-nuke/coreCommand.ts
  packages/yuudachi/src/commands/moderation/sub/anti-raid-nuke/file.ts
  packages/yuudachi/src/commands/moderation/sub/anti-raid-nuke/filter.ts
  packages/yuudachi/src/commands/moderation/sub/anti-raid-nuke/modal.ts
  packages/yuudachi/src/commands/moderation/sub/anti-raid-nuke/utils.ts
  packages/yuudachi/src/functions/anti-raid/blastOff.ts
  packages/yuudachi/src/functions/anti-raid/canBan.ts
  packages/yuudachi/src/functions/formatters/generateAntiRaidNukeReport.ts
  packages/yuudachi/src/functions/logging/formatMembersToAttachment.ts
  packages/yuudachi/src/functions/logging/generateAntiRaidNukeEmbed.ts
  packages/yuudachi/src/functions/logging/upsertAntiRaidArchiveLog.ts
  packages/yuudachi/src/interactions/moderation/anti-raid-nuke.ts
Labels: semver:minor

#1109 fix(anti-raid-nuke): full_match option when not using regex delimiters
  packages/yuudachi/src/util/parseRegex.ts
Labels: semver:minor

#1110 feat(*): prevent crash from error handling
  packages/yuudachi/package.json
  packages/yuudachi/src/events/interactionCreate.ts
Labels: priority:high, semver:patch, error handling
